### ISSUE TITLE
Proxy list is empty

### ISSUE THREAD

**Issue by Rohitsarswat** [tsankesara/Instagram-Mass-Account_Generator#10]
No of Accounts: 1
Requesting Proxies:
2022-11-25 21:36:23,161 http_request_randomizer.requests.useragent.userAgent INFO     Using local file for user agents: C:\Users\91701\PycharmProjects\pythonProject2\venv\Lib\site-packages\http_request_randomizer\requests\proxy\../data/user_agents.txt
2022-11-25 21:36:23,162 root   DEBUG    === Initialized Proxy Parsers ===
2022-11-25 21:36:23,162 root   DEBUG    	 FreeProxy parser of 'http://free-proxy-list.net' with required bandwidth: '150' KBs
2022-11-25 21:36:23,162 root   DEBUG    	 PremProxy parser of 'https://premproxy.com/list/' with required bandwidth: '150' KBs
2022-11-25 21:36:23,163 root   DEBUG    	 SslProxy parser of 'https://www.sslproxies.org' with required bandwidth: '150' KBs
2022-11-25 21:36:23,163 root   DEBUG    =================================
2022-11-25 21:36:24,434 http_request_randomizer.requests.parsers.FreeProxyParser ERROR    Provider FreeProxy failed with Attribute error: 'NoneType' object has no attribute 'find'
2022-11-25 21:36:24,434 root   DEBUG    Added 0 proxies from FreeProxy
2022-11-25 21:36:25,318 http_request_randomizer.requests.parsers.PremProxyParser WARNING  Proxy Provider url failed: https://premproxy.com/list/
2022-11-25 21:36:25,319 http_request_randomizer.requests.parsers.PremProxyParser DEBUG    Pages: set()
2022-11-25 21:36:26,128 http_request_randomizer.requests.parsers.PremProxyParser WARNING  Proxy Provider url failed: https://premproxy.com/list/
2022-11-25 21:36:26,128 root   DEBUG    Added 0 proxies from PremProxy
2022-11-25 21:36:26,715 http_request_randomizer.requests.parsers.SslProxyParser ERROR    Provider SslProxy failed with Attribute error: 'NoneType' object has no attribute 'find'
2022-11-25 21:36:26,715 root   DEBUG    Added 0 proxies from SslProxy
2022-11-25 21:36:26,715 root   DEBUG    Total proxies = 0
2022-11-25 21:36:26,715 root   DEBUG    Filtered proxies = 0
Traceback (most recent call last):
  File "C:\Users\91701\PycharmProjects\pythonProject2\accountGenerator.py", line 18, in <module>
    req_proxy = RequestProxy()
                ^^^^^^^^^^^^^^
  File "C:\Users\91701\PycharmProjects\pythonProject2\venv\Lib\site-packages\http_request_randomizer\requests\proxy\requestProxy.py", line 69, in __init__
    self.current_proxy = self.randomize_proxy()
                         ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91701\PycharmProjects\pythonProject2\venv\Lib\site-packages\http_request_randomizer\requests\proxy\requestProxy.py", line 86, in randomize_proxy
    raise ProxyListException("list is empty")
http_request_randomizer.requests.errors.ProxyListException.ProxyListException: list is empty

**Comment by JamilaAferhane** [comment]
It appears that the HTML attributes from the existing proxy providers have been modified. Try to use a proxy list https://www.proxy-list.download/api/v1/get?type=https

**Comment by JamilaAferhane** [comment]
It appears that the HTML attributes from the existing proxy providers have been modified. Try to use a proxy list https://www.proxy-list.download/api/v1/get?type=https
