### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by alphanumericaltycoon** [tsankesara/Instagram-Mass-Account_Generator#6]
Hi,

The script opens up Chrome and populates each field but is unable to progress to the second page (birthday confirmation). Here is my terminal output:

```
┌──(kali㉿kali)-[~/Desktop/accgenerator]
└─$ python3 accountGenerator.py                                                                                        1 ⨯
No of Accounts: 5
Requesting Proxies:
2021-07-31 14:51:12,075 http_request_randomizer.requests.useragent.userAgent INFO     Using local file for user agents: /home/kali/.local/lib/python3.9/site-packages/http_request_randomizer/requests/proxy/../data/user_agents.txt
2021-07-31 14:51:12,174 root   DEBUG    === Initialized Proxy Parsers ===
2021-07-31 14:51:12,174 root   DEBUG             FreeProxy parser of 'http://free-proxy-list.net' with required bandwidth: '150' KBs
2021-07-31 14:51:12,174 root   DEBUG             PremProxy parser of 'https://premproxy.com/list/' with required bandwidth: '150' KBs
2021-07-31 14:51:12,174 root   DEBUG             SslProxy parser of 'https://www.sslproxies.org' with required bandwidth: '150' KBs
2021-07-31 14:51:12,174 root   DEBUG    =================================
2021-07-31 14:51:12,667 root   DEBUG    Added 300 proxies from FreeProxy
2021-07-31 14:51:12,884 http_request_randomizer.requests.parsers.PremProxyParser WARNING  Proxy Provider url failed: https://premproxy.com/list/
2021-07-31 14:51:12,885 http_request_randomizer.requests.parsers.PremProxyParser DEBUG    Pages: set()
2021-07-31 14:51:13,116 http_request_randomizer.requests.parsers.PremProxyParser WARNING  Proxy Provider url failed: https://premproxy.com/list/
2021-07-31 14:51:13,117 root   DEBUG    Added 0 proxies from PremProxy
2021-07-31 14:51:13,379 root   DEBUG    Added 100 proxies from SslProxy
2021-07-31 14:51:13,380 root   DEBUG    Total proxies = 400
2021-07-31 14:51:13,380 root   DEBUG    Filtered proxies = 400

 
 Max No of Proxies:400
 


 
 Connecting to Proxy: 160.16.89.237:3128

IP is from: Japan
 



2021-07-31 14:51:13,383 WDM    INFO     

====== WebDriver manager ======
2021-07-31 14:51:13,383 WDM    INFO     ====== WebDriver manager ======
Current google-chrome version is 92.0.4515
2021-07-31 14:51:13,875 WDM    INFO     Current google-chrome version is 92.0.4515
Get LATEST driver version for 92.0.4515
2021-07-31 14:51:13,875 WDM    INFO     Get LATEST driver version for 92.0.4515
Driver [/home/kali/.wdm/drivers/chromedriver/linux64/92.0.4515.107/chromedriver] found in cache
2021-07-31 14:51:14,089 WDM    INFO     Driver [/home/kali/.wdm/drivers/chromedriver/linux64/92.0.4515.107/chromedriver] found in cache
/home/kali/Desktop/accgenerator/accountGenerator.py:50: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  browser = webdriver.Chrome(ChromeDriverManager().install())
2021-07-31 14:51:15,094 selenium.webdriver.remote.remote_connection DEBUG    POST http://127.0.0.1:35621/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "platformName": "any", "proxy": {"httpProxy": "160.16.89.237:3128", "ftpProxy": "160.16.89.237:3128", "sslProxy": "160.16.89.237:3128", "proxyType": "manual"}, "goog:chromeOptions": {"extensions": [], "args": []}}}, "desiredCapabilities": {"browserName": "chrome", "version": "", "platform": "ANY", "proxy": {"httpProxy": "160.16.89.237:3128", "ftpProxy": "160.16.89.237:3128", "sslProxy": "160.16.89.237:3128", "proxyType": "MANUAL"}, "goog:chromeOptions": {"extensions": [], "args": []}}}
2021-07-31 14:51:16,204 selenium.webdriver.remote.remote_connection DEBUG    Finished Request
2021-07-31 14:51:16,204 selenium.webdriver.remote.remote_connection DEBUG    POST http://127.0.0.1:35621/session/bbd83094861aaa80491dde353a0c6613/timeouts {"pageLoad": 30000}
2021-07-31 14:51:16,206 selenium.webdriver.remote.remote_connection DEBUG    Finished Request
2021-07-31 14:51:16,206 selenium.webdriver.remote.remote_connection DEBUG    POST http://127.0.0.1:35621/session/bbd83094861aaa80491dde353a0c6613/url {"url": "https://www.instagram.com/accounts/emailsignup/"}
2021-07-31 14:51:29,084 selenium.webdriver.remote.remote_connection DEBUG    Finished Request

 
 Instagram Webpage Opened 
 

2021-07-31 14:51:32,087 selenium.webdriver.remote.remote_connection DEBUG    POST http://127.0.0.1:35621/session/bbd83094861aaa80491dde353a0c6613/element {"using": "css selector", "value": "[name=\"emailOrPhone\"]"}
2021-07-31 14:51:32,101 selenium.webdriver.remote.remote_connection DEBUG    Finished Request
2021-07-31 14:51:32,101 selenium.webdriver.remote.remote_connection DEBUG    POST http://127.0.0.1:35621/session/bbd83094861aaa80491dde353a0c6613/element/3edc1f44-3714-43ed-9571-1cbfd0cc4c09/value {"text": "AllieVlada.19270@gmail.com", "value": ["A", "l", "l", "i", "e", "V", "l", "a", "d", "a", ".", "1", "9", "2", "7", "0", "@", "g", "m", "a", "i", "l", ".", "c", "o", "m"], "id": "3edc1f44-3714-43ed-9571-1cbfd0cc4c09"}
2021-07-31 14:51:32,308 selenium.webdriver.remote.remote_connection DEBUG    Finished Request

 
 Your randomize Email:AllieVlada.19270@gmail.com
 

2021-07-31 14:51:36,312 selenium.webdriver.remote.remote_connection DEBUG    POST http://127.0.0.1:35621/session/bbd83094861aaa80491dde353a0c6613/element {"using": "css selector", "value": "[name=\"fullName\"]"}
2021-07-31 14:51:36,326 selenium.webdriver.remote.remote_connection DEBUG    Finished Request
2021-07-31 14:51:36,326 selenium.webdriver.remote.remote_connection DEBUG    POST http://127.0.0.1:35621/session/bbd83094861aaa80491dde353a0c6613/element/ed64be5c-3f82-4b07-9ec4-f9314176e1bc/value {"text": "Allie Vlada", "value": ["A", "l", "l", "i", "e", " ", "V", "l", "a", "d", "a"], "id": "ed64be5c-3f82-4b07-9ec4-f9314176e1bc"}
2021-07-31 14:51:36,451 selenium.webdriver.remote.remote_connection DEBUG    Finished Request

 
 Your randomize Full Name is: Allie Vlada
 

2021-07-31 14:51:41,456 selenium.webdriver.remote.remote_connection DEBUG    POST http://127.0.0.1:35621/session/bbd83094861aaa80491dde353a0c6613/element {"using": "css selector", "value": "[name=\"username\"]"}
2021-07-31 14:51:41,468 selenium.webdriver.remote.remote_connection DEBUG    Finished Request
2021-07-31 14:51:41,468 selenium.webdriver.remote.remote_connection DEBUG    POST http://127.0.0.1:35621/session/bbd83094861aaa80491dde353a0c6613/element/00fbc8d9-d730-448a-9036-fd93ce72bb8b/value {"text": "AllieVlada.19270", "value": ["A", "l", "l", "i", "e", "V", "l", "a", "d", "a", ".", "1", "9", "2", "7", "0"], "id": "00fbc8d9-d730-448a-9036-fd93ce72bb8b"}
2021-07-31 14:51:41,611 selenium.webdriver.remote.remote_connection DEBUG    Finished Request

 
 Your randomize Username is: AllieVlada.19270
 

2021-07-31 14:51:45,617 selenium.webdriver.remote.remote_connection DEBUG    POST http://127.0.0.1:35621/session/bbd83094861aaa80491dde353a0c6613/element {"using": "css selector", "value": "[name=\"password\"]"}
2021-07-31 14:51:45,633 selenium.webdriver.remote.remote_connection DEBUG    Finished Request
2021-07-31 14:51:45,633 selenium.webdriver.remote.remote_connection DEBUG    POST http://127.0.0.1:35621/session/bbd83094861aaa80491dde353a0c6613/element/9504d981-0877-49ff-bb1b-7fda376b0409/value {"text": "RickLaLaLa!aa00912.<//213", "value": ["R", "i", "c", "k", "L", "a", "L", "a", "L", "a", "!", "a", "a", "0", "0", "9", "1", "2", ".", "<", "/", "/", "2", "1", "3"], "id": "9504d981-0877-49ff-bb1b-7fda376b0409"}
2021-07-31 14:51:45,794 selenium.webdriver.remote.remote_connection DEBUG    Finished Request

 
 Password Entred 
 

2021-07-31 14:51:47,796 selenium.webdriver.remote.remote_connection DEBUG    POST http://127.0.0.1:35621/session/bbd83094861aaa80491dde353a0c6613/element {"using": "xpath", "value": "//*[@id=\"react-root\"]/section/main/div/article/div/div[1]/div/form/div[7]/div/button"}
2021-07-31 14:51:47,813 selenium.webdriver.remote.remote_connection DEBUG    Finished Request
Traceback (most recent call last):
  File "/home/kali/Desktop/accgenerator/accountGenerator.py", line 85, in <module>
    sign_up = browser.find_element_by_xpath('//*[@id="react-root"]/section/main/div/article/div/div[1]/div/form/div[7]/div/button')
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 399, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 1012, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="react-root"]/section/main/div/article/div/div[1]/div/form/div[7]/div/button"}
  (Session info: chrome=92.0.4515.107)

                                                                                                                           
┌──(kali㉿kali)-[~/Desktop/accgenerator]
└─$                        
```

**Comment by cChimney** [comment]
outdated xpath, i believe this whole project is outdated atm btw
